#!/usr/bin/env python3
"""
Pine Renderer — GEX levels → a self-contained TradingView Pine v5 indicator
===========================================================================
Replaces the old web/Cloudflare chart-feed path. Instead of serving JSON to a
remote site, we bake the live GEX frame (walls, gamma flip/peak, volume walls,
spot, and the per-strike net-GEX profile) into a Pine *indicator* and push it
onto the local TradingView chart (see ``tv_publisher.py``).

The indicator ships ALL the data; what's *displayed* is controlled by native
``input.bool`` toggles in TradingView's indicator settings — flip them in the
UI, no round-trip needed. Only a data *refresh* re-pushes the source.

This module is PURE: ``render_pine(gex_dict) -> str``. No I/O, no network, no
TradingView dependency — so it unit-tests offline (the market can be closed).
Validate output with the MCP CLI's offline analyzer:

    python3 -m gexbot.pine_render --file tests/fixtures/gex_levels_live.sample.json > /tmp/gex.pine
    node ~/tradingview-mcp/src/cli/index.js pine analyze -f /tmp/gex.pine

Design notes
------------
* Toggle inputs have STABLE titles/types across every render — only the baked
  data constants change between refreshes. TradingView preserves input values
  on "Update on chart" when the input structure is unchanged, so the user's
  toggle choices survive a data refresh.
* GEX levels are SPX *prices*. The chart may be ES1!/SPY-proxy, offset by basis.
  The "Auto-anchor" toggle shifts every level by ``(close - SPOT)`` so SPX
  gamma levels land on whatever symbol the chart is showing. Because that
  offset is a price *series*, we draw with ``line.new``/``label.new`` on the
  last bar (hline only accepts simple/const values).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

INDICATOR_NAME = "GEXBot SPX Levels"


def _f(v) -> str:
    """Format a number as a Pine float literal, or ``na`` when missing."""
    if v is None:
        return "na"
    try:
        return f"{float(v):.2f}"
    except (TypeError, ValueError):
        return "na"


def _strike_of(v):
    """Walls are ``{strike, ...}`` dicts; flip is a bare float. Normalize."""
    if isinstance(v, dict):
        return v.get("strike")
    return v


def _pine_str(s) -> str:
    """Escape a Python string into a Pine double-quoted string literal."""
    s = "" if s is None else str(s)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _array_from(vals: list[str]) -> str:
    """Render ``array.from(...)`` or an empty typed array when no values."""
    if not vals:
        return "array.new<float>()"
    return "array.from(" + ", ".join(vals) + ")"


def render_pine(gex: dict, *, indicator_name: str = INDICATOR_NAME) -> str:
    """Render a full Pine v5 indicator source string from a GEX frame dict
    (the shape written to ``gex_levels_live.json`` by ``build_gex_result``).
    """
    spot = gex.get("spot")
    put_wall = _strike_of(gex.get("put_wall"))
    call_wall = _strike_of(gex.get("call_wall"))
    put_vol_wall = _strike_of(gex.get("put_volume_wall"))
    call_vol_wall = _strike_of(gex.get("call_volume_wall"))
    gamma_flip = _strike_of(gex.get("gamma_flip"))
    gamma_peak = _strike_of(gex.get("gamma_peak"))

    regime = gex.get("regime", "?")
    expiry = gex.get("expiry", "?")
    product = gex.get("product", "SPX")
    timestamp = gex.get("timestamp", "?")

    # Per-strike net-GEX profile → parallel arrays. Net-GEX is huge ($billions);
    # normalize to $bn for readable bar lengths and label text.
    levels = gex.get("levels") or []
    prof_strikes: list[str] = []
    prof_netgex_bn: list[str] = []
    for lv in levels:
        k = lv.get("strike")
        ng = lv.get("net_gex")
        if k is None or ng is None:
            continue
        prof_strikes.append(f"{float(k):.2f}")
        prof_netgex_bn.append(f"{float(ng) / 1e9:.4f}")

    # Header line shown in the on-chart status label.
    status = f"{product} {expiry} | {regime} | spot {_f(spot)} | {timestamp}"

    return f"""//@version=6
// ============================================================================
//  {indicator_name}
//  AUTO-GENERATED by gexbot/pine_render.py — DO NOT EDIT BY HAND.
//  Data frame: {status}
// ============================================================================
indicator({_pine_str(indicator_name)}, overlay=true, max_lines_count=500, max_labels_count=500, max_boxes_count=500)

// ===== Baked GEX data (regenerated each refresh) ============================
SPOT          = {_f(spot)}
PUT_WALL      = {_f(put_wall)}
CALL_WALL     = {_f(call_wall)}
PUT_VOL_WALL  = {_f(put_vol_wall)}
CALL_VOL_WALL = {_f(call_vol_wall)}
GAMMA_FLIP    = {_f(gamma_flip)}
GAMMA_PEAK    = {_f(gamma_peak)}
REGIME        = {_pine_str(regime)}
STATUS_TXT    = {_pine_str(status)}

var PROF_STRIKE = {_array_from(prof_strikes)}
var PROF_NETGEX = {_array_from(prof_netgex_bn)}   // $ billions

// ===== Display toggles (set these in the indicator settings) ===============
gMain = "GEX levels"
showWalls   = input.bool(true,  "Put / Call walls (OI)",   group=gMain)
showVolWall = input.bool(false, "Volume walls",            group=gMain)
showFlip    = input.bool(true,  "Gamma flip",              group=gMain)
showPeak    = input.bool(true,  "Gamma peak",              group=gMain)
showSpot    = input.bool(true,  "Spot",                    group=gMain)
showProfile = input.bool(false, "Net-GEX profile (right edge)", group=gMain)
showLabels  = input.bool(true,  "Labels",                  group=gMain)
showStatus  = input.bool(true,  "Status box",              group=gMain)

gAlign = "Alignment"
autoAnchor = input.bool(false, "Auto-anchor SPX → chart price", group=gAlign, tooltip="Shift every level by (chart close - SPX spot) so SPX gamma levels align onto an ES/SPY-proxy chart.")
manualOff  = input.float(0.0,  "Manual offset (points)", group=gAlign, step=0.25)

gStyle = "Style"
lineLen    = input.int(120, "Line length (bars)", minval=10, maxval=500, group=gStyle)
profBars   = input.int(40,  "Profile width (bars)", minval=5, maxval=200, group=gStyle)
cWall      = input.color(color.new(color.red, 0),    "Call wall",  group=gStyle)
pWall      = input.color(color.new(color.green, 0),  "Put wall",   group=gStyle)
cVol       = input.color(color.new(color.orange, 0), "Vol walls",  group=gStyle)
cFlip      = input.color(color.new(color.purple, 0), "Gamma flip", group=gStyle)
cPeak      = input.color(color.new(color.yellow, 0), "Gamma peak", group=gStyle)
cSpot      = input.color(color.new(color.gray, 0),   "Spot",       group=gStyle)

// ===== Anchoring offset (SPX price -> chart price) =========================
offset = manualOff + (autoAnchor and not na(SPOT) ? close - SPOT : 0.0)

// ===== Drawing — recomputed on the last bar only ===========================
var line[]  L = array.new<line>()
var label[] T = array.new<label>()

f_clear() =>
    for ln in L
        line.delete(ln)
    array.clear(L)
    for lb in T
        label.delete(lb)
    array.clear(T)

f_level(_price, _col, _txt, _style) =>
    if not na(_price)
        px = _price + offset
        x1 = bar_index - lineLen
        x2 = bar_index
        ln = line.new(x1, px, x2, px, color=_col, width=2, style=_style, extend=extend.right)
        array.push(L, ln)
        if showLabels
            lb = label.new(x2, px, _txt + "  " + str.tostring(px, format.mintick), style=label.style_label_left, color=color.new(_col, 80), textcolor=_col, size=size.small)
            array.push(T, lb)

if barstate.islast
    f_clear()
    if showWalls
        f_level(CALL_WALL, cWall, "Call wall", line.style_solid)
        f_level(PUT_WALL,  pWall, "Put wall",  line.style_solid)
    if showVolWall
        f_level(CALL_VOL_WALL, cVol, "Call vol wall", line.style_dotted)
        f_level(PUT_VOL_WALL,  cVol, "Put vol wall",  line.style_dotted)
    if showFlip
        f_level(GAMMA_FLIP, cFlip, "Gamma flip", line.style_dashed)
    if showPeak
        f_level(GAMMA_PEAK, cPeak, "Gamma peak", line.style_solid)
    if showSpot
        f_level(SPOT, cSpot, "Spot", line.style_dotted)

    // Net-GEX profile: short horizontal bars at the right edge, length ∝ |net|,
    // green = positive (dealers long gamma), red = negative.
    if showProfile and array.size(PROF_NETGEX) > 0
        maxAbs = 0.0
        for i = 0 to array.size(PROF_NETGEX) - 1
            maxAbs := math.max(maxAbs, math.abs(array.get(PROF_NETGEX, i)))
        if maxAbs > 0
            for i = 0 to array.size(PROF_STRIKE) - 1
                k  = array.get(PROF_STRIKE, i) + offset
                ng = array.get(PROF_NETGEX, i)
                w  = math.round(profBars * math.abs(ng) / maxAbs)
                col = ng >= 0 ? color.new(color.green, 30) : color.new(color.red, 30)
                ln = line.new(bar_index - w, k, bar_index, k, color=col, width=3)
                array.push(L, ln)

    // Status box (top-right) — frame provenance at a glance.
    if showStatus
        var table tb = table.new(position.top_right, 1, 1, border_width=1)
        table.cell(tb, 0, 0, STATUS_TXT, text_color=color.white, bgcolor=color.new(color.blue, 70), text_size=size.small)
"""


def _load(path: str | None) -> dict:
    if path:
        return json.loads(Path(path).read_text())
    return json.loads(sys.stdin.read())


def main() -> None:
    args = sys.argv[1:]
    path = None
    if "--file" in args:
        path = args[args.index("--file") + 1]
    elif "-f" in args:
        path = args[args.index("-f") + 1]
    gex = _load(path)
    sys.stdout.write(render_pine(gex))


if __name__ == "__main__":
    main()
